"""
Vault frontmatter schemas — Pydantic models for every note type.
Always validate against these before writing to the vault.
"""
from pydantic import BaseModel
from typing import Optional
from datetime import date


class JobNote(BaseModel):
    """Frontmatter schema for jobs/ notes. Auto-generated by the pipeline."""
    company: str
    title: str
    url: str
    source: str
    date_found: date
    status: str = "reviewing"  # reviewing | applied | interviewing | rejected | offer
    match_score: float
    salary_min: Optional[int] = None
    salary_max: Optional[int] = None
    location: Optional[str] = None
    remote: Optional[str] = None  # remote | hybrid | onsite | unknown
    tags: list[str] = []
    skills_required: list[str] = []
    skills_missing: list[str] = []
    jd_summary: str = ""


class SkillNote(BaseModel):
    """Frontmatter schema for skills/ notes."""
    skill: str
    category: str  # agent-framework | data | infra | ml | language | observability
    my_level: str = "none"  # none | learning | familiar | proficient | expert
    evidence: list[str] = []
    appears_in_jobs: int = 0
    priority: str = "medium"  # high | medium | low
    resources: list[str] = []


class CompanyNote(BaseModel):
    """Frontmatter schema for companies/ notes."""
    company: str
    tier: str = "unknown"  # apply-now | 3-months | 6-months | stretch
    roles_of_interest: list[str] = []
    hiring_signal: str = "unknown"  # active | slow | unknown
    why: str = ""


class ApplicationNote(BaseModel):
    """Frontmatter schema for applications/ notes. Human-maintained."""
    company: str
    title: str
    applied_date: date
    resume_variant: str = "resume.md"
    status: str = "applied"  # applied | screen | interview | offer | rejected
    contacts: list[str] = []
    next_action: str = ""
    next_action_date: Optional[date] = None
